//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 6.0.0.
// shlexec_res.rc

#define IDS_FILESYSTEMERROR                 4228
#define IDS_TWOARGS                         4230
#define IDS_ONEARG                          4231
#define IDS_CANTFIND1                       6211
#define IDS_CANTLOGON                       6442
#define IDS_NOMEMORY                        8448
#define IDS_CANTFIND2                       8449
#define IDS_TOOMANYFILES                    8451
#define IDS_BADPATH1                        8452
#define IDS_OLDOS                           8453
#define IDS_BADPROGRAM                      8454
#define IDS_ONEPROGRAMONLY                  8455
#define IDS_BADLIBRARY                      8456
#define IDS_FILELOCKED                      8457
#define IDS_BADSENDING                      8459
#define IDS_BADASSOC                        8460
#define IDS_BADFORMAT                       8461
#define IDS_CANTRUN                         8462
#define IDS_BADPATH2                        8463
#define IDS_RESTRICTION                     9728
#define IDS_CANCELBYREST                    9729

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
